### ISSUE TITLE
It does not work for me

### ISSUE THREAD

**Issue by NiceATC** [Sirillion/ZMXhudCPTHB#1]
This doesn’t work for me, just the black background appears all the time

![20200702045455_1](https://user-images.githubusercontent.com/13256614/86333655-93a20400-bc22-11ea-8bfd-8331c7c4f3d2.jpg)

**Comment by Sirillion** [comment]
You have not installed it correctly. It requires DMT to work, so you either need to install it via the Mod Launcher which patches it automatically or download and run the DMT tool to patch the engine manually.
